project_id = "dedalus-interview"

[api]
enabled = true
port = 54521
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54522
shadow_port = 54520
major_version = 17

[db.migrations]
enabled = true

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[realtime]
enabled = false

[edge_runtime]
enabled = false

[analytics]
enabled = false
